### ISSUE TITLE
Create CI/CD pipeline

### ISSUE THREAD

**Issue by XinpingHuangE** [DevopsShopcarts/shopcarts#58]
**As a** [role]  
 **I need** [function]  
 **So that** [benefit]  
   
 ### Details and Assumptions
 * [document what you know]
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given [some context]
 When [certain action is taken]
 Then [the outcome of action is observed]
 ```

**Comment by AntonioTan** [comment]
Hello, teams. Now the CI/CD runs successfully on the cloud for the first time. I did the following fixes according to problems on the cloud.
1. limit resource given to postgresql service in kubernetes
2. fix problem of delete shopcart scenario in bdd test
